-- CreateTable
CREATE TABLE `TripPlan` (
    `id` VARCHAR(191) NOT NULL,
    `projectName` VARCHAR(191) NOT NULL,
    `conferenceStartDate` VARCHAR(191) NULL,
    `conferenceEndDate` VARCHAR(191) NULL,
    `startDate` VARCHAR(191) NOT NULL,
    `endDate` VARCHAR(191) NOT NULL,
    `hasPersonalLeave` BOOLEAN NOT NULL DEFAULT false,
    `leaveStartDate` VARCHAR(191) NULL,
    `leaveEndDate` VARCHAR(191) NULL,
    `location` VARCHAR(191) NOT NULL,
    `country` VARCHAR(191) NOT NULL,
    `countryGroup` INTEGER NOT NULL,
    `hostOrganization` VARCHAR(191) NOT NULL,
    `budgetCode` VARCHAR(191) NOT NULL,
    `paymentMethod` ENUM('credit', 'cash', 'advance') NOT NULL DEFAULT 'advance',
    `estimatedBudget` INTEGER NOT NULL DEFAULT 0,
    `status` ENUM('A1_DRAFT', 'A2_SEARCHING', 'A3_MEMO_DRAFTED', 'A3_A4_WAITING_SIGNATURE', 'A4_EPAYMENT_PREP', 'A4_EXPORTED', 'FIORI_PENDING', 'WAITING_CASH_ADVANCE', 'A5_UPLOADING_RECEIPTS', 'TRIP_CLEARED') NOT NULL DEFAULT 'A1_DRAFT',
    `travelers` JSON NOT NULL,
    `itemPaymentMethods` JSON NULL,
    `customBudgetItems` JSON NULL,
    `flightOptions` JSON NULL,
    `selectedFlight` JSON NULL,
    `insuranceOptions` JSON NULL,
    `selectedInsurance` JSON NULL,
    `memo` JSON NULL,
    `ePaymentData` JSON NULL,
    `receipts` JSON NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    INDEX `TripPlan_status_idx`(`status`),
    INDEX `TripPlan_createdAt_idx`(`createdAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
